INSERT INTO FABRICANTE (NOME) VALUES ('Fabrimar');
INSERT INTO FABRICANTE (NOME) VALUES ('Fabriterra');

INSERT INTO CATEGORIA(NOME) VALUES ('Chuveiro');
INSERT INTO CATEGORIA(NOME) VALUES ('Vaso Sanitário');

INSERT INTO PRODUTO(NOME, SALDO, SALDO_MINIMO, CATEGORIA_ID, FABRICANTE_ID)
VALUES ('Modelo A', 40, 5, 1, 1);

INSERT INTO PRODUTO(NOME, SALDO, SALDO_MINIMO, CATEGORIA_ID, FABRICANTE_ID)
VALUES ('Modelo B', 50, 8, 2, 2);

